// <auto-generated />
using System;
using Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(PermisosDBContext))]
    [Migration("20201112060602_Relations2")]
    partial class Relations2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Data.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PermisoID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidosEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("FechaPermiso")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TipoPermisoId")
                        .HasColumnName("TipoPermisoID")
                        .HasColumnType("int");

                    b.HasKey("PermisoId");

                    b.HasIndex("TipoPermisoId");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("Entities.Data.TipoPermiso", b =>
                {
                    b.Property<int>("TipoPermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TipoPermisoID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("TipoPermisoId");

                    b.ToTable("TipoPermiso");
                });

            modelBuilder.Entity("Entities.Data.Permiso", b =>
                {
                    b.HasOne("Entities.Data.TipoPermiso", "TipoPermiso")
                        .WithMany("Permiso")
                        .HasForeignKey("TipoPermisoId")
                        .HasConstraintName("FK_Permiso_TipoPermiso");
                });
#pragma warning restore 612, 618
        }
    }
}
